#!/bin/bash
bee=bee-0.33.2.far
if [ ! -e $bee ]; then
    bee=$JAVA_HOME/lib/bee-0.33.2.jar
    if [ ! -e $bee ]; then
        echo $bee is not found locally, try to download it from network.
        curl -#L -o $bee https://jitpack.io/com/github/teletha/bee/0.33.2/bee-0.33.2.jar
    fi
fi
java -javaagent:$bee -cp $bee bee.Bee "$@"